# Generated by Django 5.0.7 on 2024-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_file'),
        ),
    ]
