# Generated by Django 5.0.7 on 2024-08-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0002_alter_homework_homework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erpapp.student'),
            preserve_default=False,
        ),
    ]
