# Generated by Django 5.0.7 on 2024-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0004_alter_lesson_unique_together_remove_lesson_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='first_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
